# -*- coding: utf-8 -*-
"""swieta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJDNi5LNWUyVhPjCXKekwLBiCaxXZdiu
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# Tytuł aplikacji Streamlit
st.title("🎅 Święty Mikołaj w Streamlit (Matplotlib)")
st.caption("Wygenerowany za pomocą bibliotek Matplotlib i Streamlit.")

def draw_santa():
    """Funkcja rysująca figurę Świętego Mikołaja za pomocą Matplotlib."""

    # Ustawienia figury
    fig, ax = plt.subplots(figsize=(8, 10))
    ax.set_xlim(-10, 10)
    ax.set_ylim(-10, 15)
    ax.set_aspect('equal')
    ax.axis('off') # Usuń osie

    # --- PARAMETRY ---
    X_BODY = 0
    Y_BODY = -10
    BODY_WIDTH = 6
    BODY_HEIGHT = 10
    RED = '#D62828'
    WHITE = '#F0F0F0'
    SKIN = '#FADADD'
    BLACK = '#1E1E1E'
    GOLD = '#FFC300'

    # --- 1. KORPUS I NOGI ---
    # Korpus (Czerwony Płaszcz)
    body = patches.Rectangle((X_BODY - BODY_WIDTH/2, Y_BODY), BODY_WIDTH, BODY_HEIGHT, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(body)

    # Białe obszycie na dole płaszcza
    body_fur_bottom = patches.Rectangle((X_BODY - BODY_WIDTH/2, Y_BODY), BODY_WIDTH, 1, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(body_fur_bottom)

    # Pasek (czarny)
    belt = patches.Rectangle((X_BODY - BODY_WIDTH/2, -1.5), BODY_WIDTH, 1.5, color=BLACK, ec=BLACK, lw=1.5)
    ax.add_patch(belt)

    # Klamra (żółty)
    buckle = patches.Rectangle((X_BODY - 1.5, -2), 3, 2.5, color=GOLD, ec=BLACK, lw=1.5)
    ax.add_patch(buckle)

    # Nogi (Czerwone Spodnie)
    leg_left = patches.Rectangle((X_BODY - 2.5, -10), 2, 2, color=RED, ec=BLACK, lw=1.5)
    leg_right = patches.Rectangle((X_BODY + 0.5, -10), 2, 2, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(leg_left)
    ax.add_patch(leg_right)

    # Buty (czarne)
    boot_left = patches.Rectangle((X_BODY - 3, -12), 3, 2, color=BLACK, ec=BLACK, lw=1.5)
    boot_right = patches.Rectangle((X_BODY + 0, -12), 3, 2, color=BLACK, ec=BLACK, lw=1.5)
    ax.add_patch(boot_left)
    ax.add_patch(boot_right)

    # --- 2. GŁOWA, BRODA I CZAPKA ---
    Y_HEAD = 5
    # Twarz (jasny beż)
    face = patches.Circle((X_BODY, Y_HEAD), 2.5, color=SKIN, ec=BLACK, lw=1.5)
    ax.add_patch(face)

    # Broda (użycie okręgów i łuku, aby uzyskać kształt)
    beard_base = patches.Circle((X_BODY, Y_HEAD - 2.5), 3.5, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(beard_base)
    beard_cutout = patches.Rectangle((X_BODY - 2.5, Y_HEAD - 0.5), 5, 3, color=SKIN, ec='none') # Wycięcie, by odsłonić twarz
    ax.add_patch(beard_cutout)

    # Wąsy
    mustache_left = patches.Circle((X_BODY - 1.5, Y_HEAD - 1), 1.5, color=WHITE, ec=BLACK, lw=1.5)
    mustache_right = patches.Circle((X_BODY + 1.5, Y_HEAD - 1), 1.5, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(mustache_left)
    ax.add_patch(mustache_right)

    # Nos (czerwony)
    nose = patches.Circle((X_BODY, Y_HEAD - 0.5), 0.5, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(nose)

    # Oczy (czarne)
    ax.plot([X_BODY - 1, X_BODY + 1], [Y_HEAD + 0.5, Y_HEAD + 0.5], 'o', markersize=6, color=BLACK)


    # Czapka (Czerwony Trójkąt)
    hat_red = patches.Polygon([(-4.5, Y_HEAD + 0.5), (4.5, Y_HEAD + 0.5), (0, Y_HEAD + 8)], closed=True, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(hat_red)

    # Białe futerko na dole czapki
    hat_fur = patches.Rectangle((-4.5, Y_HEAD), 9, 1, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(hat_fur)

    # Pompon (biały)
    pompon = patches.Circle((0, Y_HEAD + 8), 1.5, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(pompon)


    # --- 3. RĘCE ---
    # Ręka Lewa
    arm_left = patches.Rectangle((X_BODY - 5, 2), 2, 4, angle=45, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(arm_left)
    # Rękawiczka Lewa
    glove_left = patches.Circle((X_BODY - 5, 4), 1, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(glove_left)

    # Ręka Prawa
    arm_right = patches.Rectangle((X_BODY + 3, 2), 2, 4, angle=-45, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(arm_right)
    # Rękawiczka Prawa
    glove_right = patches.Circle((X_BODY + 5, 4), 1, color=WHITE, ec=BLACK, lw=1.5)
    ax.add_patch(glove_right)


    # --- 4. WOREK Z PREZENTAMI ---
    # Worek (na lewo od Mikołaja)
    bag = patches.Wedge((-7, -5), 4, 270, 90, color='brown', ec=BLACK, lw=1.5, width=4)
    ax.add_patch(bag)
    bag_top = patches.Rectangle((-10, -5), 6, 2, color='brown', ec=BLACK, lw=1.5)
    ax.add_patch(bag_top)
    # Szczyt worka (zawiązanie)
    bag_tie = patches.Rectangle((-10, -3), 6, 0.5, color=RED, ec=BLACK, lw=1.5)
    ax.add_patch(bag_tie)

    # Prezenty (wystające z worka)
    # Niebieski
    gift_blue = patches.Rectangle((-9, -2.5), 1.5, 2, color='blue', ec=BLACK, lw=1)
    ax.add_patch(gift_blue)
    # Zielony
    gift_green = patches.Rectangle((-7, -1.5), 1, 1.5, color='green', ec=BLACK, lw=1)
    ax.add_patch(gift_green)
    # Żółty
    gift_yellow = patches.Rectangle((-8.5, -0.5), 1.5, 0.5, color='yellow', ec=BLACK, lw=1)
    ax.add_patch(gift_yellow)

    # Zwrócenie figury do Streamlit
    return fig

# Rysowanie Mikołaja za pomocą Streamlit
st.pyplot(draw_santa())